### ISSUE TITLE
Parsing raw comment string.

### ISSUE THREAD

**Issue by typhonrt** [es-joy/jsdoccomment#13]
Greets,

Edit: I should preface this by saying this is a "nice to have" request. An alternate solution is cleaning leading / trailing delimiters IE `/**` / `*/` from a comment string then using `parseComment`.

----

I'm already using `comment-parser`, but for AST modification and reconstruction of comment blocks working with `jsdoccomment` is much easier. I have already verified that I can accomplish my goal via AST modification w/ `jsdoccomment`, however I am working with a raw comment block string and that makes `parseComment` difficult to work with presently.

At minimum I need access to `parseInlineTags` which is not exported from the package or perhaps it makes sense to add a `parseCommentString` or `parseCommentRaw` which accepts a complete string comment block. 

Either adding `export {default as parseInlineTags} from './parseInlineTags.js';` in `src/index.js`

or an example of `parseCommentString`:

```js
/**
 * Accepts a comment string and converts it into `comment-parser` AST.
 * @param {string} comment
 * @returns {import('./index.js').JsdocBlockWithInline}
 */
const parseCommentString = (comment) => {
  const [block] = commentParser(comment, {
    // @see https://github.com/yavorskiy/comment-parser/issues/21
    tokenizers: getTokenizers()
  });
  return parseInlineTags(block);
};
```

I'd be glad to submit a PR, but prefer to have a bit of discussion first.

**Comment by brettz9** [comment]
Sure, welcome to submit a PR for `parseCommentString` and/or exporting `parseInlineTags`. Probably shouldn't make `parseComment` dependent on `parseCommentString` though as would add a function call to a frequently used function.

**Comment by typhonrt** [comment]
So, in the PR I did expand the argument accepted to `parseComment` to take a token object or string. This doesn't expand the API surface, so I think it's the best solution. I added one additional test for a comment block string. 

---

I also in a separate [fork of a fork](https://github.com/typhonjs-svelte-scratch/jsdoccomment-docs) produce [API documentation](https://typhonjs-svelte-scratch.github.io/jsdoccomment-docs/) that is easily hosted on GH pages. I have a new zero config CLI frontend for TypeDoc called [typedoc-pkg](https://www.npmjs.com/package/@typhonjs-typedoc/typedoc-pkg) that produces docs from a well configured `package.json` w/ type declarations which is already setup w/ `jsdoccomments`. Only requirement for that is adding the dependency in `package.json` and a new NPM script `docs`. I think it really helps API discovery and seeing exactly what is exposed in the declarations. Glad to submit a PR for that if of interest.

---

Yeah.. I've been meaning to touch bases as I have been working on a lot of tooling in the last year. There is one project that I think can have some `eslint` usage for the JSDoc plugin potentially or possibly I will eventually get around to creating a separate plugin. This is for `no-undefined-types` rule. I have produced API docs for the entire Typescript built-in libs for ESM / DOM APIs via [ts-lib-docs](https://www.npmjs.com/package/@typhonjs-typedoc/ts-lib-docs). I expose the symbol names and this can certainly cover the entire ESM / DOM APIs to provide comprehensive coverage w/ `no-undefined-types`. Here is a link for the [ESM API JSON data](https://github.com/typhonjs-typedoc/ts-lib-docs/blob/main/data/2023/esm/reflection-names.json).

**Comment by brettz9** [comment]
> So, in the PR I did expand the argument accepted to `parseComment` to take a token object or string. This doesn't expand the API surface, so I think it's the best solution. I added one additional test for a comment block string.

Yeah, that seems most reasonable to me, too.

> I also in a separate [fork of a fork](https://github.com/typhonjs-svelte-scratch/jsdoccomment-docs) produce [API documentation](https://typhonjs-svelte-scratch.github.io/jsdoccomment-docs/) that is easily hosted on GH pages. I have a new zero config CLI frontend for TypeDoc called [typedoc-pkg](https://www.npmjs.com/package/@typhonjs-typedoc/typedoc-pkg) that produces docs from a well configured `package.json` w/ type declarations which is already setup w/ `jsdoccomments`. Only requirement for that is adding the dependency in `package.json` and a new NPM script `docs`. I think it really helps API discovery and seeing exactly what is exposed in the declarations. Glad to submit a PR for that if of interest.

I'm a little unclear—what does `typedoc-pkg` add above `typedoc`? The ability to build docs relative to `exports`? In any case, sure, a PR should be welcome.

> Yeah.. I've been meaning to touch bases as I have been working on a lot of tooling in the last year. There is one project that I think can have some `eslint` usage for the JSDoc plugin potentially or possibly I will eventually get around to creating a separate plugin. This is for `no-undefined-types` rule. I have produced API docs for the entire Typescript built-in libs for ESM / DOM APIs via [ts-lib-docs](https://www.npmjs.com/package/@typhonjs-typedoc/ts-lib-docs). I expose the symbol names and this can certainly cover the entire ESM / DOM APIs to provide comprehensive coverage w/ `no-undefined-types`. Here is a link for the [ESM API JSON data](https://github.com/typhonjs-typedoc/ts-lib-docs/blob/main/data/2023/esm/reflection-names.json).

"ESM" refers to ES Modules, but it seems to me you're talking about ES (globals), no?

As you may be aware, we could use some improvements on our `no-undefined-types` in `eslint-plugin-jsdoc` (I guess you mean to supply the globals--if so, can that JSON be fairly readily updated as TypeScript is updated?).

**Comment by typhonrt** [comment]
> I'm a little unclear—what does `typedoc-pkg` add above `typedoc`? The ability to build docs relative to `exports`? In any case, sure, a PR should be welcome.

At a high level `typedoc-pkg` parses `package.json` for `types` including full parsing of the `exports` fields including sub-path patterns. It will automatically configure TypeDoc for those entry points. You can also specify other export conditions to create the docs from source. It also pulls together all of the TypeDoc resources I've created including a "theme augmentation" of the default TypeDoc theme which adds several features and a nicer UI (left-hand navigation). The automatic entry point to actual package export name is accomplished with this theme as well as that is a feature TypeDoc has yet to support by configuration. One more big thing it does is make it easy to configure via CLI options inclusion of the full end-to-end linking of the TS lib built in library API docs. IE if you reference `Promise` and any other symbol in the ES / DOM libraries it will link to actual TS API docs, so not only is there docs for a given project, but complete end-to-end docs. I've had a general discussion w/ the maintainer of TypeDoc and tentatively the likelihood of upstreaming a lot of my efforts into TypeDoc itself will happen later this year. 

I definitely don't want to come across as pushing any of the tooling that I've worked on, but there is some rather good support for creating solid type declarations from ESM source instead of just using raw TSC which does have issues / pitfalls and then `typedoc-pkg` for instant API docs without having to bother with configuration beyond a properly setup `package.json`. IE two zero configuration tools. Just bringing most of this up as I gather you are ESM forward in dev and I saw that you are using raw TSC for types. 

Once I finish up the current work that is leveraging `jsdoccomment` I'll look into creating the optimum types / API docs for jsdoccomment and you can take a look. No worries if any PR is accepted. I've been using your handy work for a while, so chance to give back a little as it makes sense.

> "ESM" refers to ES Modules, but it seems to me you're talking about ES (globals), no?

Yep, a small oversight there. I've corrected that in `typedoc-pkg`: `es` instead of `esm` for the API linking and when I refresh `ts-lib-docs` for 2024 TS built-in library additions will name it `es` there as well. 
 
> As you may be aware, we could use some improvements on our `no-undefined-types` in `eslint-plugin-jsdoc` (I guess you mean to supply the globals--if so, can that JSON be fairly readily updated as TypeScript is updated?).

Yeah.. For quite some time in my eslint configs I personally use I've added the relevant ES / TS lib symbols that I use to cover the use of the `no-undefined-types` rule everything else is covered via `import types`. I have yet to get around to creating a plugin utilizing all of the symbols generated by `ts-lib-docs`, but this could possibly be something that can be leveraged by `eslint-plugin-jsdoc` itself.  The approach taken is to create a combined declaration file that adds / merges updates through the TS built-in libs processed by year then exporting JSON from it. So it can be updated at will with new TS built-in library additions. You can directly access the JSON data via `import dataES from '@typhonjs-typedoc/ts-lib-docs/json/esm/reflection-names/2023';`  Likewise for the DOM API `import dataDOM from '@typhonjs-typedoc/ts-lib-docs/json/dom/reflection-names/2023';`

**Comment by brettz9** [comment]
> > I'm a little unclear—what does `typedoc-pkg` add above `typedoc`? The ability to build docs relative to `exports`? In any case, sure, a PR should be welcome.
> 
> At a high level `typedoc-pkg` parses `package.json` for `types` including full parsing of the `exports` fields including sub-path patterns. It will automatically configure TypeDoc for those entry points. You can also specify other export conditions to create the docs from source. It also pulls together all of the TypeDoc resources I've created including a "theme augmentation" of the default TypeDoc theme which adds several features and a nicer UI (left-hand navigation). The automatic entry point to actual package export name is accomplished with this theme as well as that is a feature TypeDoc has yet to support by configuration. One more big thing it does is make it easy to configure via CLI options inclusion of the full end-to-end linking of the TS lib built in library API docs. IE if you reference `Promise` and any other symbol in the ES / DOM libraries it will link to actual TS API docs, so not only is there docs for a given project, but complete end-to-end docs. I've had a general discussion w/ the maintainer of TypeDoc and tentatively the likelihood of upstreaming a lot of my efforts into TypeDoc itself will happen later this year.
> 
> I definitely don't want to come across as pushing any of the tooling that I've worked on, but there is some rather good support for creating solid type declarations from ESM source instead of just using raw TSC which does have issues / pitfalls and then `typedoc-pkg` for instant API docs without having to bother with configuration beyond a properly setup `package.json`. IE two zero configuration tools. Just bringing most of this up as I gather you are ESM forward in dev and I saw that you are using raw TSC for types.

Yes, sure. I'm very open to your tooling, but would really like a better idea of what some of those issues/pitfalls are, if you find a chance to elaborate.

> Once I finish up the current work that is leveraging `jsdoccomment` I'll look into creating the optimum types / API docs for jsdoccomment and you can take a look. No worries if any PR is accepted. I've been using your handy work for a while, so chance to give back a little as it makes sense.

Sounds great.

> > "ESM" refers to ES Modules, but it seems to me you're talking about ES (globals), no?
> 
> Yep, a small oversight there. I've corrected that in `typedoc-pkg`: `es` instead of `esm` for the API linking and when I refresh `ts-lib-docs` for 2024 TS built-in library additions will name it `es` there as well.

Cool.

> > As you may be aware, we could use some improvements on our `no-undefined-types` in `eslint-plugin-jsdoc` (I guess you mean to supply the globals--if so, can that JSON be fairly readily updated as TypeScript is updated?).
> 
> Yeah.. For quite some time in my eslint configs I personally use I've added the relevant ES / TS lib symbols that I use to cover the use of the `no-undefined-types` rule everything else is covered via `import types`. I have yet to get around to creating a plugin utilizing all of the symbols generated by `ts-lib-docs`, but this could possibly be something that can be leveraged by `eslint-plugin-jsdoc` itself. 

Yes, some JSON should be sufficient.

> The approach taken is to create a combined declaration file that adds / merges updates through the TS built-in libs processed by year then exporting JSON from it. So it can be updated at will with new TS built-in library additions. You can directly access the JSON data via `import dataES from '@typhonjs-typedoc/ts-lib-docs/json/esm/reflection-names/2023';` Likewise for the DOM API `import dataDOM from '@typhonjs-typedoc/ts-lib-docs/json/dom/reflection-names/2023';`

Great.

**Comment by typhonrt** [comment]
> Yes, sure. I'm very open to your tooling, but would really like a better idea of what some of those issues/pitfalls are, if you find a chance to elaborate.

I'll be making an explainer / tutorial video in the coming months that goes through all of the toolchain / process from declaration generation to API documentation for ESM first developers. 

So, [esm-d-ts](https://www.npmjs.com/package/@typhonjs-build-test/esm-d-ts) is the zero config declaration tooling. There are many useful features particularly for library authors. I've been working on it for over two years and use it regularly for simple to very complex (my larger Svelte based framework) configurations. I've just completed plugin support for it and the first plugin supports JS / JSDoc oriented Svelte 4 components; special handling of comment blocks in Svelte components is what I'm using `jsdoccomment` for as things go. The default Svelte declaration tooling does not produce viable semantically / self-documenting declarations w/ JSDoc support. 

`esm-d-ts` is built on top of other really great OSS tooling like Guy Bedford's `es-module-lexer`. This is how given an entry point source file `esm-d-ts` can lexically analyze all connected source files and automatically configure TSC programmatically without any `tssconfig.json`. With the plugin support now it's possible to add support for anything that can be transpiled to ESM like `.svelte` files.

Another big benefit is that the declarations produced are automatically bundled. This produces a single clean declaration file for the entire module. Every NPM package sub-path export gets a modern bundled declaration file. This converts all `import type` references to actual types and makes all sorts of downstream tooling work better from IDE display of types to TypeDoc. For instance I noticed in generating documentation from existing `jsdoccomment` types that TypeDoc gets confused by `import('./index.js').<TYPE ALIAS>` and thinks it is referring to the module as a whole since `./index.js` is also the entry point.  [Example of that here](https://typhonjs-svelte-scratch.github.io/jsdoccomment-docs/functions/parseComment.html). This gets disambiguated with `esm-d-ts` and bundled types.

Another really handy feature is that you _can_ use `.ts` files to define such as complex type aliases and interfaces, and anything that is too difficult to represent in JSDoc. You can reference these declarations through import types w/ JSDoc and `esm-d-ts` includes the "external" `.ts` declarations in the generated declarations along with the rest of the JSDoc generated declarations. An example of how that is useful with `@implements` is mentioned below.

Some specific problem areas below, but not an exhaustive list. TSC has several rough spots when generating types for JS.  The nice thing is all of this can be corrected through AST transformation as necessary in the generation process. So current problems and new features can be added now that might take a while for Typescript maintainers to get around to as JSDoc / JS support isn't high on the priority list.

-----

- Any static private symbols are mangled and worse made public in generated declarations.

```js
export class Test
{
   static #foo = 'Should be private';

   /**
    * Should be private
    */
   static #bar() {}
}
````

TSC by default produces:

```typescript
declare class Test {
  static '__#1@#foo': string;
  /**
   * Should be private
   */
  static '__#1@#bar'(): void;
}
````

where it should be:

```typescript
declare class Test {}
```

-----

- To much subtler issues. TSC changes setter accessor argument names are changed to `arg`. This has recently become a problem when producing public API documentation from declarations w/ TypeDoc 0.25.7+ released in January as TypeDoc now verifies `@param` names to what is represented in the declarations and will drop the comments if the names mismatch.

Source class:
```js
export class Test
{
   /**
    * @returns {string} Returns foo.
    */
   get foo() { return 'foo'; }

   /**
    * @param {string} foo - Sets foo.
    */
   set foo(foo) { this._foo = foo; }
}
```

TSC generates:
```typescript
declare class Test {
  /**
   * @param {string} foo - Sets foo.
   */
  set foo(arg: string);
  /**
   * @returns {string} Returns foo.
   */
  get foo(): string;
  _foo: string;
}
```

Should generate:
```typescript
declare class Test {
  /**
   * @param {string} foo - Sets foo.
   */
  set foo(foo: string);
  /**
   * @returns {string} Returns foo.
   */
  get foo(): string;
  _foo: string;
}
```

-----

- Support for filtering out `@internal` tagged symbols is spotty across TS versions; was a private configuration option / now public, but not reliable. `esm-d-ts` absolutely removes them from generated declarations. This is also configurable to filter based on any JSDoc tag.

-----

Currently not supported by TSC, but possible w/ `esm-d-ts` (see: `https://github.com/microsoft/TypeScript/issues/49905`):

- import types in `@implements {import('./types').AnInterface}`.
  - The import type is synthetically added as an import in generated declarations and `inherits AnInterface` is added to the associated class declaration.

-----

`esm-d-ts` also provides some handy capabilities when it comes to generating self-documenting / semantic declarations such as preserving any comment block in the entry point source file that use `@module` or `@packageDocumentation` which TypeDoc uses to display a description of the module / entry point / package itself. TSC by default will strip this comment block.

-----
