### ISSUE TITLE
`commentParserToESTree`: Working with full comment blocks and removal of new lines / empty description lines.

### ISSUE THREAD

**Issue by typhonrt** [es-joy/jsdoccomment#15]
So,

The last problem I think I will run into re: `jsdoccomment` and processing full comment blocks is that `commentParserToESTree` compacts the AST data for description lines. While the parsing in `parseComment` is setup to `preserve` through the AST generation from `comment-parser` there is forced compaction in `commentParserToESTree`. This occurs on [line 366](https://github.com/es-joy/jsdoccomment/blob/main/src/commentParserToESTree.js#L366).

Change `if (description) {` to `if (typeof description === 'string' && delimiter !== '/**') {` and the compaction doesn't occur. There may be a better test to change this to and of course a reason for the compaction for the type of processing that you are utilizing `jsdoccomment` for as things go. For my purposes of modifying a complete comment block it is important to preserve the extra new lines / empty description lines particularly around the use of markdown in comment blocks which won't be interpreted correctly by downstream tooling like TypeDoc without them.

My general suggestion is adding an additional option to `commentParserToESTree` for `spacing` just like `comment-parser` and it can default to `compact`, but if `preserve` is passed then new lines are kept for description generation. Perhaps you can suggest a better conditional test that you might prefer rather than using `delimiter` for `if (typeof description === 'string' && delimiter !== '/**') {` as that is just a quick test I used to determine the source of the issue I'm facing. Maybe: `if ((spacing === 'compact' && description) || (spacing === 'preserve' && delimiter !== '/**'))`.

I'd be glad to work up a PR with the changes after a bit of discussion.

**Comment by brettz9** [comment]
I think you are saying that line 366 triggers compacting, but I don't see where the compacting actually occurs. `holder.descriptionLines.push` in line 368 is just optional AST to have separate lines, whereas line 395 doesn't seem to be compacting per se. Is the issue in line 395 because we are not always adding a newline there? It would help if you had a sample JSDoc block which was triggering this ES block that we could discuss.

**Comment by typhonrt** [comment]
I'll provide some examples tomorrow, but you can see this clearly if you print out the AST of a comment block from `parseComment` then the output of `commentParserToESTree`. I too started investigating around line 395 potentially adding an extra new line, but w/ JS an empty string evaluates to false in a bare conditional `if (description)` when description is an empty string evaluates to `false`.

**Comment by typhonrt** [comment]
I submitted a PR that adds a `spacing` option to `commentParserToESTree` that mirrors the same option available in `comment-parser`. When spacing is set to `preserve` empty lines are preserved in the AST parsing and subsequent conversion back to a string via `estreeToString`. Two new tests were added.

Here is some additional data / example of the problem.

1: Original test comment block with empty lines.

![comment-original](https://github.com/es-joy/jsdoccomment/assets/311473/0ee13c49-2076-4c70-845c-d4605c94d92b)

2: Test logging around `if (description)` showing when `description` is an empty string it evaluates to false. 

![commentParserToESTree-line_365-pre-post](https://github.com/es-joy/jsdoccomment/assets/311473/482f4ab6-f0f2-4340-badb-0c2dc8943ba9)

3:Test logging output showing skipped empty lines (3 & 5); line 0 should be skipped as it is the delimiter line `/**`:

![test-logging-output](https://github.com/es-joy/jsdoccomment/assets/311473/e38cfa26-5f1e-4012-8fe4-edee9dfdbc46)

4: For a complex markdown comment block what should look like the following.

![documentation-correct](https://github.com/es-joy/jsdoccomment/assets/311473/ea2491f6-f3e3-4838-9497-b48a035010db)

5: It gets mangled in TypeDoc without the empty line spacing.

![documentation-incorrect](https://github.com/es-joy/jsdoccomment/assets/311473/d79beaef-faa6-4a3c-8f80-92c9102a288d)

**Comment by brettz9** [comment]
Thanks for the extra info.

I think though that if we are adding a "preserve" mode, that we should add the description even for `/**` (and the line break before `*/` which is not always present) and leave it to consumers to trim if they wish. There are plenty of users who do like to use the 0th line.

**Comment by typhonrt** [comment]
That is to be expected hence the question previously as the conditional I proposed and initially implemented in the PR works for "normal" well formatted comment blocks. I'll start working on permutations. Also checking with estreeToString in the tests. Any chance you can list as many permutations as you can come up with that are known that should parse? I can see this growing into several additional test cases for the `preserve` option.

IE: This should parse in `preserve` mode, but it won't currently, etc. Like:
```js
/** A comment */
```

```js
/** It should 
 * 
 * parse */
```

**Comment by typhonrt** [comment]
So upon further investigation I'd like to clarify two more things. 

------

1) Regardless of `spacing` being `compact` or `preserve` there is likely some unwanted behavior in the existing code. For instance `/** Should parse */` when run through `commentParserToESTree` then `estreeToString` produces `/** /** Should parse */`. This is a separate issue / code point to examine which is [lines 248 - 268](https://github.com/es-joy/jsdoccomment/blob/main/src/commentParserToESTree.js#L248-L268)

I have so far made the following changes to detect a single line comment block and not include the `delimiter` / `postDelimiter` in the single entry of `descriptionLines` if so and the output will match the input:
```js
      if (end && !tag) {
        ast.terminal = end;
        if (description) {
          if (lastTag) {
            ast.hasPreterminalTagDescription = 1;
          } else {
            ast.hasPreterminalDescription = 1;
          }

          const holder = lastTag || ast;
          holder.description += (holder.description ? '\n' : '') + description;

          // In the end tag handling; check if there are any description lines and if not then this is a 
          // one line comment block. 
          const isDelimiterLine = holder.descriptionLines.length === 0 &&
            delimiter === '/**';

          holder.descriptionLines.push({
            // If a one line comment block do not include the delimiter.
            delimiter: isDelimiterLine ? '' : delimiter,
            description,
            // If a one line comment block do not include the postDelimiter.
            postDelimiter: isDelimiterLine ? '' : postDelimiter,
            initial,
            type: 'JsdocDescriptionLine'
          });
        }
        return;
      }
```

As an aside the changes I proposed for the if conditional `if ((spacing === 'compact' && description) || (spacing === 'preserve' && delimiter !== '/**'))` later on in `commentParserToESTree` won't be reached due to the early return in the above mentioned block. So far things seem safe in that regard for one line comment blocks, but more exhaustive tests need to be completed.

------

2) Is the intention to reformat comment block strings when passing the ESTree AST through `estreeToString`?

Should this:
```js
/**
 * Should parse one line. */
```

Result in this:
```js
/**
 * Should parse one line.
 */
```

Rather than exactly matching the input comment block? This is just for comparisons with new tests I'm writing. I think it's valid to rewrite the comment blocks into well formatted blocks on output, but just want to clarify the intention.

**Comment by brettz9** [comment]
> That is to be expected hence the question previously as the conditional I proposed and initially implemented in the PR works for "normal" well formatted comment blocks. I'll start working on permutations. Also checking with estreeToString in the tests. Any chance you can list as many permutations as you can come up with that are known that should parse? I can see this growing into several additional test cases for the `preserve` option.
> 
> IE: This should parse in `preserve` mode, but it won't currently, etc. Like:
> 
> ```js
> /** A comment */
> ```
> 
> ```js
> /** It should 
>  * 
>  * parse */
> ```

I think you've covered them; i.e., 0th line, intervening lines, and final line. The existing tests should give an idea of permutations, as we have full testing coverage (besides for one file which had been covered when `jsdoccomment` was just a part of `eslint-plugin-jsdoc`).

**Comment by brettz9** [comment]
> So upon further investigation I'd like to clarify two more things.
> 
>     1. Regardless of `spacing` being `compact` or `preserve` there is likely some unwanted behavior in the existing code. For instance `/** Should parse */` when run through `commentParserToESTree` then `estreeToString` produces `/** /** Should parse */`. This is a separate issue / code point to examine which is [lines 248 - 268](https://github.com/es-joy/jsdoccomment/blob/main/src/commentParserToESTree.js#L248-L268)

Feel free to prepare any PRs to fix these issues. `eslint-plugin-jsdoc` does not use all these APIs, so we might not have discovered as many bugs like this.

>     2. Is the intention to reformat comment block strings when passing the ESTree AST through `estreeToString`?
> 
> 
> Should this:
> 
> ```js
> /**
>  * Should parse one line. */
> ```
> 
> Result in this:
> 
> ```js
> /**
>  * Should parse one line.
>  */
> ```
> 
> Rather than exactly matching the input comment block? This is just for comparisons with new tests I'm writing. I think it's valid to rewrite the comment blocks into well formatted blocks on output, but just want to clarify the intention.

It'd be ideal, I think, if we could allow both via config, since "well-formatted" is a bit subjective, (even if newlines at the beginning and end are more typical) and I tend to favor the ability to either have full round-trippability or something akin to linting (for "fixing" the formatting). But that isn't critical now.

**Comment by typhonrt** [comment]
OK.. I have everything working smoothly and the associated PR is updated with new tests and ready for review. In the process of roundtrip testing for `parseComment` -> `commentParserToESTree` -> `estreeToString` I also fixed the 0th / single line issue of the duplicated leading `/**` delimiter as these changes go hand in hand.
